# Generated by Django 2.1.5 on 2019-01-14 08:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Noter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.FileField(upload_to='')),
                ('titel', models.CharField(max_length=100)),
                ('beskrivelse', models.TextField(help_text='Beskriv hvilke noter du har taget')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('usr', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
