# Generated by Django 2.1.5 on 2019-01-14 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bagvask', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='noter',
            name='titel',
            field=models.CharField(max_length=50),
        ),
    ]
