# Generated by Django 2.1.5 on 2019-01-14 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bagvask', '0002_auto_20190114_1342'),
    ]

    operations = [
        migrations.AlterField(
            model_name='noter',
            name='beskrivelse',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='noter',
            name='note',
            field=models.FileField(upload_to='noter/'),
        ),
        migrations.AlterField(
            model_name='noter',
            name='titel',
            field=models.CharField(max_length=255),
        ),
    ]
