# Generated by Django 2.1 on 2018-09-16 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontpage', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='m1',
            name='columnlen',
            field=models.IntegerField(default=120),
            preserve_default=False,
        ),
    ]
