# Generated by Django 2.1 on 2018-09-16 12:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('frontpage', '0004_timetable'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Timetable',
        ),
    ]
