# Generated by Django 2.1 on 2018-09-17 21:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('frontpage', '0007_auto_20180917_1624'),
    ]

    operations = [
        migrations.CreateModel(
            name='Maskiner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('maskine', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Tables',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('starttid', models.CharField(max_length=255)),
                ('sluttid', models.CharField(max_length=255)),
                ('columnlen', models.IntegerField()),
                ('maskine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='frontpage.Maskiner')),
            ],
        ),
        migrations.RemoveField(
            model_name='m1',
            name='usr',
        ),
        migrations.RemoveField(
            model_name='m2',
            name='usr',
        ),
        migrations.RemoveField(
            model_name='m3',
            name='usr',
        ),
        migrations.DeleteModel(
            name='M1',
        ),
        migrations.DeleteModel(
            name='M2',
        ),
        migrations.DeleteModel(
            name='M3',
        ),
        migrations.AddField(
            model_name='tables',
            name='usr',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
