# Generated by Django 2.1 on 2018-09-18 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontpage', '0008_auto_20180917_2129'),
    ]

    operations = [
        migrations.CreateModel(
            name='Avtime',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.CharField(max_length=255)),
            ],
        ),
    ]
