# Generated by Django 2.1 on 2018-09-18 21:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('frontpage', '0009_auto_20180918_1714'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Avtime',
        ),

    ]
