# Generated by Django 2.1 on 2018-09-27 16:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('frontpage', '0013_auto_20180927_1613'),
    ]

    operations = [

        migrations.AlterField(
            model_name='tables',
            name='maskine',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='frontpage.Maskiner'),
        ),
    ]
