# Generated by Django 2.1 on 2018-09-27 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontpage', '0014_auto_20180927_1624'),
    ]

    operations = [

        migrations.AlterField(
            model_name='tables',
            name='maskine',
            field=models.CharField(choices=[('Sønderhus vask 3', 'Sønderhus vask 3'), ('Sønderhus vask 2', 'Sønderhus vask 2'), ('Sønderhus vask 1', 'Sønderhus vask 1'), ('Damgården vask', 'Damgården vask')], default='Sønderhus vask 1', max_length=255),
        ),
        migrations.AlterField(
            model_name='taken',
            name='maskine',
            field=models.CharField(choices=[('Sønderhus vask 3', 'Sønderhus vask 3'), ('Sønderhus vask 2', 'Sønderhus vask 2'), ('Sønderhus vask 1', 'Sønderhus vask 1'), ('Damgården vask', 'Damgården vask')], default='Sønderhus vask 1', max_length=255),
        ),
        migrations.DeleteModel(
            name='Maskiner',
        ),
    ]
