# Generated by Django 2.1 on 2018-10-09 20:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('frontpage', '0015_auto_20180927_1639'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
