# Generated by Django 2.1.2 on 2018-11-02 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontpage', '0016_delete_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='tables',
            name='color',
            field=models.CharField(default='#fff', max_length=255),
            preserve_default=False,
        ),
    ]
