# Generated by Django 2.1.5 on 2019-01-21 22:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tables',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('maskine', models.CharField(choices=[('Sønderhus vask 3', 'Sønderhus vask 3'), ('Sønderhus vask 2', 'Sønderhus vask 2'), ('Sønderhus vask 1', 'Sønderhus vask 1'), ('Damgårdens vask', 'Damgårdens vask')], default='Sønderhus Vask 1', max_length=255)),
                ('starttid', models.CharField(choices=[('8:00', '8:00'), ('9:00', '9:00'), ('10:00', '10:00'), ('11:00', '11:00'), ('12:00', '12:00'), ('13:00', '13:00'), ('14:00', '14:00'), ('15:00', '15:00'), ('16:00', '16:00'), ('17:00', '17:00'), ('18:00', '18:00'), ('19:00', '19:00'), ('20:00', '20:00'), ('21:00', '21:00')], default='8:00', max_length=255)),
                ('sluttid', models.CharField(choices=[('8:00', '8:00'), ('9:00', '9:00'), ('10:00', '10:00'), ('11:00', '11:00'), ('12:00', '12:00'), ('13:00', '13:00'), ('14:00', '14:00'), ('15:00', '15:00'), ('16:00', '16:00'), ('17:00', '17:00'), ('18:00', '18:00'), ('19:00', '19:00'), ('20:00', '20:00'), ('21:00', '21:00')], default='10:00', max_length=255)),
                ('columnlen', models.IntegerField()),
                ('color', models.CharField(max_length=255)),
                ('usr', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Taken',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.CharField(max_length=255)),
                ('maskine', models.CharField(choices=[('Sønderhus vask 3', 'Sønderhus vask 3'), ('Sønderhus vask 2', 'Sønderhus vask 2'), ('Sønderhus vask 1', 'Sønderhus vask 1'), ('Damgårdens vask', 'Damgårdens vask')], default='Sønderhus vask 1', max_length=255)),
            ],
        ),
    ]
