# Generated by Django 2.1.5 on 2019-01-26 11:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vaskeside', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Taken',
        ),
    ]
